FROM node:24.14-slim

# Set the working directory.
WORKDIR /usr/src/app

# Copy package.json and yarn.lock.
COPY package.json yarn.lock ./

# Install dependencies.
RUN yarn global add @angular/cli@19
RUN yarn install --frozen-lockfile

# Expose the port for the development server.
EXPOSE 4200

# Start the development server. The poll flag allows for live reloading.
CMD ["ng", "serve", "--host", "0.0.0.0", "--disable-host-check", "--poll", "200"]
