ARG NODE_VERSION=24.12.0-alpine
ARG NGINX_VERSION=alpine3.22
ARG APP_VERSION=0.0.0
ARG SOURCE_URL=unknown

FROM node:${NODE_VERSION} AS builder

# Set the working directory inside the container.
WORKDIR /usr/src/app

# Copy app dependencies.
COPY package.json yarn.lock ./

# Install app dependencies.
RUN --mount=type=cache,target=/usr/local/share/.cache/yarn \
    yarn install --frozen-lockfile

# Copy app source.
COPY . /usr/src/app

# Pre-build.
RUN yarn prebuild

# Build app.
RUN yarn build -- --output-path=./dist/out --configuration production

FROM nginxinc/nginx-unprivileged:${NGINX_VERSION} AS runner

# Copy the NGINX configuration file.
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the built app to the NGINX server with proper ownership.
COPY --chown=nginx:nginx --from=builder /usr/src/app/dist/out/browser /usr/share/nginx/html

# Use a built-in non-root user for security best practices.
USER nginx

# Expose port 4200 to allow HTTP traffic.
EXPOSE 4200
