server {
  include /etc/nginx/mime.types;

  listen 4200;

  gzip on;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
  gzip_comp_level 6;
  gzip_min_length 256;
  gzip_vary on;

  # Serve the application
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html =404;
  }
}
