events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Port $server_port;

    server {
        listen 80;

        location /api {
            proxy_pass http://la-backend:8000/api;
            proxy_read_timeout 30s;
            proxy_connect_timeout 30s;
        }

        location /users {
            proxy_pass http://la-backend:8000/users;
            proxy_read_timeout 30s;
            proxy_connect_timeout 30s;
        }

        location /admin {
            proxy_pass http://la-backend:8000/admin;
            proxy_read_timeout 30s;
            proxy_connect_timeout 30s;
        }

        location /static {
            proxy_pass http://la-backend:8000/static;
            proxy_read_timeout 30s;
            proxy_connect_timeout 30s;
        }

        location / {
            proxy_pass http://la-frontend:4200;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
    }
}
