# Generated by Django 4.2.27 on 2025-12-08 13:25

from django.db import migrations

from user.models import GroupName
from user.permissions import ANNOTATOR_PERMISSIONS, MASTER_ANNOTATOR_PERMISSIONS


PERMISSION_MAP = {
    GroupName.MASTER_ANNOTATORS: MASTER_ANNOTATOR_PERMISSIONS,
    GroupName.ANNOTATORS: ANNOTATOR_PERMISSIONS,
}


def create_groups(apps, schema_editor):
    """
    Creates user groups for annotators and master annotators and assigns permissions to them.
    """
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    for group_name, perms in PERMISSION_MAP.items():
        group, created = Group.objects.get_or_create(name=group_name.value)
        for perm_codename in perms:
            try:
                app_label, codename = perm_codename
                permission = Permission.objects.get(
                    content_type__app_label=app_label,
                    codename=codename,
                )
                group.permissions.add(permission)
            except Permission.DoesNotExist:
                print(
                    f"Permission {perm_codename} does not exist and cannot be added to group {group_name}."
                )


def delete_groups(apps, schema_editor):
    """
    Deletes the user groups created for annotators and master annotators.
    """
    Group = apps.get_model("auth", "Group")

    for group_name in PERMISSION_MAP.keys():
        try:
            group = Group.objects.get(name=group_name)
            group.delete()
        except Group.DoesNotExist:
            print(f"Group {group_name} does not exist and cannot be deleted.")


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_sitedomain"),
        ("problem", "0008_delete_knowledgebase"),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
