# Generated by Django 4.2.20 on 2025-11-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_sitedomain"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("annotator", "Annotator"),
                    ("master_annotator", "Master Annotator"),
                    ("visitor", "Visitor"),
                ],
                default="visitor",
                help_text="Visitors can browse problems and parses. Annotators can annotate non-locked problems. Master Annotators can manage users, change problem lock status, and review annotations.",
                max_length=20,
            ),
        ),
    ]
