# Generated by Django 4.2.27 on 2025-12-11 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("problem", "0007_alter_problem_options"),
        ("annotation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        help_text="A detailed description of the label, indicating when it should be used."
                    ),
                ),
            ],
            options={
                "ordering": ["text"],
            },
        ),
        migrations.CreateModel(
            name="Labeling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attached_at", models.DateTimeField(auto_now_add=True)),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this label was removed from the problem.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes explaining why this label was added or removed.",
                    ),
                ),
                (
                    "attached_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labelings_attached",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labelings",
                        to="annotation.label",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labelings",
                        to="problem.problem",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who removed this label.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labelings_removed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-attached_at"],
                "permissions": [
                    ("delete_own_labeling", "Can remove own labeling from problems"),
                    ("delete_any_labeling", "Can remove any labeling from problems"),
                ],
                "indexes": [
                    models.Index(
                        fields=["problem", "removed_at"],
                        name="annotation__problem_e7ac7b_idx",
                    ),
                    models.Index(
                        fields=["label", "removed_at"],
                        name="annotation__label_i_a229d2_idx",
                    ),
                ],
            },
        ),
    ]
