# Generated by Django 4.2.27 on 2026-01-21 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("problem", "0007_alter_problem_options"),
        ("annotation", "0002_label_labeling"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this annotation was removed from the problem.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes explaining why this annotation was added or removed.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_annotations",
                        to="annotation.label",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="problem.problem",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who removed this annotation.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss_removed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="annotation.annotationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "delete_own_label_annotation",
                        "Can remove own label annotation from problems",
                    ),
                    (
                        "delete_any_label_annotation",
                        "Can remove any label annotation from problems",
                    ),
                ],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="knowledgebaseannotation",
            name="knowledge_base",
        ),
        migrations.AddField(
            model_name="knowledgebaseannotation",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss_created",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="knowledgebaseannotation",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Optional notes explaining why this annotation was added or removed.",
            ),
        ),
        migrations.AddField(
            model_name="knowledgebaseannotation",
            name="problem",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="problem.problem",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="knowledgebaseannotation",
            name="removed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this annotation was removed from the problem.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="knowledgebaseannotation",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who removed this annotation.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss_removed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebaseannotation",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="annotation.annotationsession",
            ),
        ),
        migrations.DeleteModel(
            name="Labeling",
        ),
        migrations.AddIndex(
            model_name="labelannotation",
            index=models.Index(
                fields=["problem", "removed_at"], name="annotation__problem_7b6d4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labelannotation",
            index=models.Index(
                fields=["label", "removed_at"], name="annotation__label_i_243aa0_idx"
            ),
        ),
    ]
