# Generated by Django 4.2.30 on 2026-08-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_alter_problemannotation_entailment_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebaseannotation',
            name='relationship',
            field=models.CharField(choices=[('equal', 'Equal'), ('subset', 'Subset'), ('disjoint', 'Disjoint')], default='equal', max_length=255),
        ),
    ]
