# Generated by Django 4.2.20 on 2025-05-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("sick", "Sick"), ("fracas", "FraCaS")], max_length=255
                    ),
                ),
                ("content", models.JSONField()),
            ],
        ),
    ]
