# Generated by Django 4.2.20 on 2025-05-22 11:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FracasProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fracas_id", models.IntegerField(unique=True)),
                (
                    "question",
                    models.CharField(
                        help_text="The question from the original FraCaS problem. 4 problems do not have a question.",
                        max_length=255,
                    ),
                ),
                (
                    "hypothesis",
                    models.CharField(
                        help_text="The answer formulated as a hypothesis by McCartney.",
                        max_length=255,
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        help_text='The answer from the original FraCaS problem. Most are "Yes", "No", or "Don\'t know", but not always.',
                        max_length=255,
                    ),
                ),
                (
                    "fracas_answer",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("unknown", "Unknown"),
                            ("undef", "Undef"),
                        ],
                        help_text="The answer constrained to one of a fixed set of values by McCartney.",
                        max_length=20,
                    ),
                ),
                (
                    "fracas_non_standard",
                    models.BooleanField(
                        help_text='Indicates whether the answer in the origianl FraCaS problem is non-standard (i.e. not "Yes", "No", or "Don\'t know")'
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        help_text="Note given by McCartney to explain issues arising during translation to XML."
                    ),
                ),
                (
                    "section_name",
                    models.CharField(
                        help_text="The section name from the original FraCaS problem.",
                        max_length=255,
                    ),
                ),
                (
                    "subsection_name",
                    models.CharField(
                        help_text="The subsection name from the original FraCaS problem.",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SickProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pair_id", models.IntegerField(unique=True)),
                ("sentence_one", models.CharField(max_length=255)),
                ("sentence_two", models.CharField(max_length=255)),
                (
                    "entailment_label",
                    models.CharField(
                        choices=[
                            ("neutral", "Neutral"),
                            ("contradiction", "Contradiction"),
                            ("entailment", "Entailment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "relatedness_score",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FracasPremise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "premise_index",
                    models.IntegerField(
                        help_text="The index of the premise in the original FraCaS problem."
                    ),
                ),
                (
                    "premise",
                    models.CharField(
                        help_text="The premise from the original FraCaS problem.",
                        max_length=255,
                    ),
                ),
                (
                    "fracas_problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premises",
                        to="problem.fracasproblem",
                    ),
                ),
            ],
            options={
                "unique_together": {("fracas_problem", "premise_index")},
            },
        ),
    ]
