# Generated by Django 4.2.20 on 2025-05-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FracasProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fracas_id', models.IntegerField(unique=True)),
                ('question', models.CharField(help_text='The question from the original FraCaS problem. 4 problems do not have a question.', max_length=255)),
                ('hypothesis', models.CharField(help_text='The answer formulated as a hypothesis by McCartney.', max_length=255)),
                ('answer', models.CharField(help_text='The answer from the original FraCaS problem. Most are "Yes", "No", or "Don\'t know", but not always.', max_length=255)),
                ('fracas_answer', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown'), ('undef', 'Undef')], help_text='The answer constrained to one of a fixed set of values by McCartney.', max_length=20)),
                ('fracas_non_standard', models.BooleanField(help_text='Indicates whether the answer in the origianl FraCaS problem is non-standard (i.e. not "Yes", "No", or "Don\'t know")')),
                ('note', models.TextField(help_text='Note given by McCartney to explain issues arising during translation to XML.')),
                ('section_name', models.CharField(help_text='The section name from the original FraCaS problem.', max_length=255)),
                ('subsection_name', models.CharField(help_text='The subsection name from the original FraCaS problem.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FracasPremise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premise_index', models.IntegerField(help_text='The index of the premise in the original FraCaS problem.')),
                ('premise', models.CharField(help_text='The premise from the original FraCaS problem.', max_length=255)),
                ('fracas_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premises', to='problem.fracasproblem')),
            ],
            options={
                'unique_together': {('fracas_problem', 'premise_index')},
            },
        ),
    ]
