# Generated by Django 4.2.20 on 2025-06-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="type",
            field=models.CharField(
                choices=[("sick", "Sick"), ("fracas", "FraCaS"), ("snli", "SNLI")],
                max_length=255,
            ),
        ),
    ]
