# Generated by Django 4.2.20 on 2025-07-08 10:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0002_alter_problem_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="content",
            new_name="extra_data",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="type",
        ),
        migrations.AddField(
            model_name="problem",
            name="dataset",
            field=models.CharField(
                choices=[
                    ("sick", "Sick"),
                    ("fracas", "FraCaS"),
                    ("snli", "SNLI"),
                    ("user", "User"),
                ],
                default="user",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="entailment_label",
            field=models.CharField(
                choices=[
                    ("neutral", "Neutral"),
                    ("entailment", "Entailment"),
                    ("contradiction", "Contradiction"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="hypothesis",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="premises",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=512), default=list, size=None
            ),
        ),
    ]
