# Generated by Django 4.2.20 on 2025-08-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0003_rename_content_problem_extra_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="problem",
            name="premises",
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity1", models.CharField(max_length=255)),
                ("entity2", models.CharField(max_length=255)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("equal", "Equal"),
                            ("not_equal", "Not Equal"),
                            ("subset", "Subset"),
                            ("superset", "Superset"),
                        ],
                        default="equal",
                        max_length=255,
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_bases",
                        to="problem.problem",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="problem",
            name="hypothesis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hypothesis_problems",
                to="problem.sentence",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="premises",
            field=models.ManyToManyField(
                related_name="premise_problems", to="problem.sentence"
            ),
        ),
    ]
