# Generated by Django 4.2.20 on 2025-07-30 08:55

from django.db import migrations, models
import django.db.models.deletion


def migrate_fields_to_extra_data(apps, schema_editor):
    """
    Migrate existing hypothesis and premises strings to Sentence objects; save ids in Problem.extra_data.
    """
    Problem = apps.get_model("problem", "Problem")
    Sentence = apps.get_model("problem", "Sentence")

    for problem in Problem.objects.all():
        if problem.hypothesis:
            hypothesis_sentence, _ = Sentence.objects.get_or_create(
                text=problem.hypothesis
            )
            problem.extra_data["temp_hypothesis_id"] = hypothesis_sentence.id

        if problem.premises:
            problem_sentence_ids = []
            for sentence_text in problem.premises:
                sentence, _ = Sentence.objects.get_or_create(text=sentence_text)
                problem_sentence_ids.append(sentence.id)
            problem.extra_data["temp_premise_ids"] = problem_sentence_ids

        problem.save()


def migrate_extra_data_to_fields(apps, schema_editor):
    """
    Reverse migration: retrieve ids from Problem.extra_data; use objects to populate hypothesis and premises fields.
    """
    problem_model = apps.get_model("problem", "Problem")
    sentence_model = apps.get_model("problem", "Sentence")

    for problem in problem_model.objects.all():
        if problem.extra_data.get("temp_hypothesis_id"):
            hypothesis_sentence = sentence_model.objects.get(
                id=problem.extra_data["temp_hypothesis_id"]
            )
            problem.hypothesis = hypothesis_sentence.text
            problem.extra_data.pop("temp_hypothesis_id", None)

        if problem.extra_data.get("temp_premise_ids"):
            premise_sentences = sentence_model.objects.filter(
                    id__in=problem.extra_data["temp_premise_ids"]
                )
            problem.premises = [sentence.text for sentence in premise_sentences]
            problem.extra_data.pop("temp_premise_ids", None)

        problem.save()


def migrate_extra_data_to_sentences(apps, schema_editor):
    """
    Migrate extra_data fields to Sentence objects.
    """
    Problem = apps.get_model("problem", "Problem")
    Sentence = apps.get_model("problem", "Sentence")

    for problem in Problem.objects.all():
        if "temp_hypothesis_id" in problem.extra_data:
            hypothesis_sentence = Sentence.objects.get(
                id=problem.extra_data["temp_hypothesis_id"]
            )
            problem.extra_data.pop("temp_hypothesis_id", None)
            problem.hypothesis = hypothesis_sentence

        if "temp_premise_ids" in problem.extra_data:
            premises_sentences = Sentence.objects.filter(
                id__in=problem.extra_data["temp_premise_ids"]
            )
            problem.extra_data.pop("temp_premise_ids", None)
            problem.premises.set(premises_sentences)

        problem.save()


def migrate_sentences_to_extra_data(apps, schema_editor):
    """
    Migrate Sentence objects to extra_data fields.
    """
    Problem = apps.get_model("problem", "Problem")

    for problem in Problem.objects.all():
        if problem.hypothesis:
            problem.extra_data["temp_hypothesis_id"] = problem.hypothesis.id

        if problem.premises.exists():
            problem.extra_data["temp_premise_ids"] = list(
                problem.premises.values_list("id", flat=True)
            )

        problem.save()


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0003_rename_content_problem_extra_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.RunPython(
            code=migrate_fields_to_extra_data,
            reverse_code=migrate_extra_data_to_fields,
        ),
        migrations.RemoveField(
            model_name="problem",
            name="premises",
        ),
        migrations.AddField(
            model_name="problem",
            name="premises",
            field=models.ManyToManyField(
                related_name="premise_problems",
                to="problem.sentence",
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="hypothesis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hypothesis_problems",
                to="problem.sentence",
                null=True,
            ),
        ),
        migrations.RunPython(
            code=migrate_extra_data_to_sentences,
            reverse_code=migrate_sentences_to_extra_data,
        ),
        migrations.AlterField(
            model_name="problem",
            name="hypothesis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hypothesis_problems",
                to="problem.sentence",
            ),
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity1", models.CharField(max_length=255)),
                ("entity2", models.CharField(max_length=255)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("equal", "Equal"),
                            ("not_equal", "Not Equal"),
                            ("subset", "Subset"),
                            ("superset", "Superset"),
                        ],
                        default="equal",
                        max_length=255,
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_bases",
                        to="problem.problem",
                    ),
                ),
            ],
        ),
    ]
