# Generated by Django 4.2.20 on 2025-08-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_sentence_remove_problem_premises_knowledgebase_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnowledgeBase',
        ),
    ]
