# Generated by Django 4.2.20 on 2025-09-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0004_sentence_remove_problem_premises_knowledgebase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="base",
            field=models.ForeignKey(
                blank=True,
                help_text="The base problem from which this problem was derived, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_problems",
                to="problem.problem",
            ),
        ),
    ]
