# Generated by Django 4.2.27 on 2025-12-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0005_problem_base"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={
                "permissions": [
                    ("view_gold_problems", "Can view problems marked as gold"),
                    ("view_silver_problems", "Can view problems marked as silver"),
                    ("view_hidden_problems", "Can view hidden problems that are marked as hidden"),
                    ("copy_problems", "Can copy problems"),
                    ("change_problem_status", "Can change status of a problem (gold/silver)"),
                    ("change_problem_visibility", "Can change problem visibility (hidden/visible)"),
                ]
            },
        ),
    ]
