# Generated by Django 4.2.27 on 2025-12-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0006_alter_problem_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={
                "permissions": [
                    ("view_gold_problems", "Can view gold problems"),
                    ("view_silver_problems", "Can view silver problems"),
                    ("view_hidden_problems", "Can view hidden problems"),
                    ("copy_problems", "Can copy problems"),
                    ("change_problem_status", "Can change problem status"),
                    ("change_problem_visibility", "Can change problem visibility"),
                ]
            },
        ),
    ]
