# Generated by Django 4.2.27 on 2026-02-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0003_labelannotation_and_more"),
        ("problem", "0007_alter_problem_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KnowledgeBase",
        ),
    ]
