# Generated by Django 4.2.27 on 2025-12-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0007_alter_problem_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KnowledgeBase",
        ),
    ]
