# Generated by Django 4.2.30 on 2026-06-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0008_delete_knowledgebase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="entailment_label",
            field=models.CharField(
                choices=[
                    ("neutral", "Neutral"),
                    ("entailment", "Entailment"),
                    ("contradiction", "Contradiction"),
                    ("conflict", "Conflict"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=255,
            ),
        ),
    ]
