# Generated by Django 4.2.27 on 2026-05-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0008_delete_knowledgebase"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
