# Generated by Django 4.2.30 on 2026-08-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0009_alter_problem_entailment_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
