# Generated by Django 4.2.30 on 2026-08-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0010_problem_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="gold",
            field=models.BooleanField(default=False),
        ),
    ]
