# Generated by Django 5.2.17 on 2026-09-16 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0012_problem_langpro_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedKnowledgeBaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity1', models.CharField(max_length=255)),
                ('entity2', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('equal', 'Equal'), ('subset', 'Subset'), ('disjoint', 'Disjoint')], default='equal', max_length=255)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_kb_items', to='problem.problem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
